/**
 * Scaffold job sidecar I/O (Section 21.6.2).
 * File: `<base_folder>/scaffold_jobs.yaml`.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import * as YAML from 'yaml';
import type { ScaffoldJob, ScaffoldJobsFile } from '../domain/types.ts';
import { writeFileAtomic } from '../util/fs.ts';

export function scaffoldJobsPath(baseFolder: string): string {
  return join(baseFolder, 'scaffold_jobs.yaml');
}

export function loadScaffoldJobs(baseFolder: string): ScaffoldJobsFile {
  const path = scaffoldJobsPath(baseFolder);
  if (!existsSync(path)) return { jobs: [] };
  const text = readFileSync(path, 'utf8');
  const parsed = YAML.parse(text);
  if (!parsed || typeof parsed !== 'object') return { jobs: [] };
  const jobs = Array.isArray((parsed as { jobs?: unknown }).jobs) ? (parsed as { jobs: ScaffoldJob[] }).jobs : [];
  return { jobs };
}

export function writeScaffoldJobs(baseFolder: string, file: ScaffoldJobsFile): void {
  const path = scaffoldJobsPath(baseFolder);
  const yaml = YAML.stringify(file, { lineWidth: 0 });
  writeFileAtomic(path, '# AUTO-GENERATED by GaggleDispatch.\n' + yaml);
}

export function upsertJob(file: ScaffoldJobsFile, job: ScaffoldJob): ScaffoldJobsFile {
  const idx = file.jobs.findIndex((j) => j.slug === job.slug);
  const jobs = [...file.jobs];
  if (idx === -1) jobs.push(job);
  else jobs[idx] = job;
  return { jobs };
}

export function removeJobBySlug(file: ScaffoldJobsFile, slug: string): ScaffoldJobsFile {
  return { jobs: file.jobs.filter((j) => j.slug !== slug) };
}
